import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CartProvider, { CartContextType } from "@/context/CartContext";
import NavBar from "@/components/nav/NavBar";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AuthProvider>
                    <CartProvider>
                        <NavBar />
                        <main className="pb-[100px] sm:pb-0">{children}</main>
                    </CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
